name: Build and Test (humble)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: humble
      - name: Build rm_auto_aim
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rm_auto_aim
          target-ros2-distro: humble
          skip-tests: true
      - name: Test armor_detector
        run: |
          source /opt/ros/humble/setup.sh
          cd ros_ws
          colcon test --packages-select armor_detector --event-handlers console_cohesion+ --return-code-on-test-failure
      - name: Test armor_tracker
        run: |
          source /opt/ros/humble/setup.sh
          cd ros_ws
          colcon test --packages-select armor_tracker --event-handlers console_cohesion+ --return-code-on-test-failure
